import Foundation

/// C-3: クリップボード入力バリアントが読み取ってよい内容かの純粋な判定。
///
/// **型検査を文字列読み取りより先に行う。** Secure Input・concealed系フラグ・
/// 自己再帰マーカー・item数はすべて`NSPasteboard`の型情報だけで判定できる。
/// 本文を読むのはそれらを通過したあとに限ることで、拒否経路が
/// クリップボードの本文へ依存しないことを保証する。
enum ClipboardSourceReadPolicy {
    enum Decision: Equatable {
        case text(String)
        case empty
        case nonText
        case rejectedSecureInput
        case rejectedConcealed
        case rejectedSelfGenerated
        case tooLong(actual: Int, maximum: Int)
    }

    /// 自己再帰（自分が書いた出力を自分で読み戻すこと）を防ぐ。文字列は
    /// `PasteboardPasteTransaction`が唯一の出どころで、ここでは複製しない。
    static let selfGeneratedOwnerType = PasteboardPasteTransaction.ownerTypeRawValue

    private static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "org.nspasteboard.TransientType"
    ]

    static func decision(
        secureInputEnabled: Bool,
        itemCount: Int,
        availableTypes: [String],
        readString: () -> String?,
        maximumCharacters: Int
    ) -> Decision {
        guard !secureInputEnabled else { return .rejectedSecureInput }
        // 自己再帰の判定をconcealedより先に置く。`PasteboardPasteTransaction`は自分の
        // itemに`org.nspasteboard.TransientType`も付ける（`:93`）ため、concealedを
        // 先に見ると自分が書いた出力が常に`.rejectedConcealed`として報告され、
        // 理由コードから自己再帰を見分けられなくなる。どちらでも拒否はするが、
        // ログとUI文言のために理由を正しく分ける。
        guard !availableTypes.contains(selfGeneratedOwnerType) else {
            return .rejectedSelfGenerated
        }
        guard !availableTypes.contains(where: concealedTypes.contains) else {
            return .rejectedConcealed
        }
        guard itemCount == 1 else { return .nonText }
        guard let string = readString() else { return .nonText }
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return .empty }
        guard trimmed.count <= maximumCharacters else {
            return .tooLong(actual: trimmed.count, maximum: maximumCharacters)
        }
        return .text(trimmed)
    }
}

/// クリップボード読み取り失敗を利用者へ伝える案内文。純粋関数にしてテスト可能にする。
enum ClipboardSourceGuidanceCopy {
    /// `.text`はエラーではないので`nil`を返す。それ以外は必ず文言を返す。
    /// `default:`は書かない。ケース追加時にコンパイラへ検出させるため。
    static func message(for decision: ClipboardSourceReadPolicy.Decision, language: AppLanguage) -> String? {
        switch decision {
        case .text:
            return nil
        case .empty:
            return AppLocalizer.text(
                "クリップボードが空です。使いたい文章をコピーしてから、もう一度お試しください。",
                language: language
            )
        case .nonText:
            return AppLocalizer.text(
                "クリップボードにテキストが入っていません。文章をコピーしてから、もう一度お試しください。",
                language: language
            )
        case .rejectedSecureInput:
            return AppLocalizer.text(
                "安全な入力が有効なため、クリップボードを読み取れません。パスワード入力などを閉じてから、もう一度お試しください。",
                language: language
            )
        case .rejectedConcealed:
            return AppLocalizer.text(
                "このクリップボードの内容は、パスワード管理アプリなどが秘匿指定したものです。AIへは渡しません。",
                language: language
            )
        case .rejectedSelfGenerated:
            return AppLocalizer.text(
                "クリップボードにはKoedex自身の出力が入っています。AIへは渡しません。編集したい文章をコピーしてから、もう一度お試しください。",
                language: language
            )
        case .tooLong(_, let maximum):
            return AppLocalizer.format(
                "クリップボードの文章が%d文字を超えています。短くしてから、もう一度お試しください。",
                language: language,
                maximum
            )
        }
    }
}
